---

- name: "0: read configuration from device and push data to GitHub"
  hosts: all
  gather_facts: no
  vars: 
    - intfs: {}
    - sot_dir: "{{ inventory_dir }}"
  connection: network_cli

  tasks: 

  - name: "1.0: checkout SoT from GitHub"
    git: 
      repo: https://github.com/maxrainer/net-demo-data.git
      dest: "{{ sot_dir }}"
      update: no
    run_once: true
    connection: local
  
  - name: "1.1: clean local host variable files"
    file: 
     state: absent
     path: "{{ sot_dir }}/host_vars/{{ inventory_hostname }}.yaml"
    connection: local
  
  - name: "2.0: Cisco IOS Router"
    block:
      - name: IOS Router
        ios_facts: 
          gather_network_resources: 
            - interfaces
            - l3_interfaces
        register: _facts
        become: true
      - include_tasks: "./includes/write_hostvars.yml"
    when: ansible_network_os == 'ios' and inventory_hostname not in groups['switch']

  - name: "2.1: Cisco IOS Switch"
    block:
      - name: IOS Switches
        ios_facts: 
          gather_network_resources: 
            - all
        register: _facts
        become: true
      - include_tasks: "./includes/write_hostvars.yml"
    when: ansible_network_os == 'ios' and inventory_hostname in groups['switch']
  
  - name: "3.0: Cisco IOS-XR"
    block: 
      - name: IOSXR
        iosxr_facts: 
          gather_network_resources: 
            - all
        register: _facts
        become: true
      - include_tasks: "./includes/write_hostvars.yml"
    when: ansible_network_os == 'iosxr'

  - name: "4.0: Cisco Nexus NXOS"
    block: 
      - name: NXOS
        nxos_facts: 
          gather_network_resources: 
            - all
        register: _facts
      - include_tasks: "./includes/write_hostvars.yml"
    when: ansible_network_os == 'nxos'

  - name: "5.0: push SoT to GitHub"
    command: "{{ item }}"
    loop:
      - "git add ."
      - "git commit -m 'by ansible'"
      - "git push"
    args: 
      chdir: "{{ sot_dir }}"
    run_once: true
    connection: local
    