---

- name: push config to device
  hosts: all
  gather_facts: no
  vars: 
    - intf_cache: {}

  tasks:

  - name: debug
    debug: 
      var: hostvars[inventory_hostname]

  - name: debug
    debug: 
      var: intfs

  - set_fact: 
      _intfs_cache: "{{ lookup('template', './templates/interfaces.j2') | from_yaml }}"
  
  - name: debug2
    debug: 
      var: _intfs_cache

    
  - name: write interface to Cisco IOS
    ios_interfaces: 
      config: "{{ _intfs_cache }}"
      state: merged
    become: true
    when: ansible_network_os == 'ios'

  - name: write interface to Cisco IOSXR
    iosxr_interfaces: 
      config: "{{ _intfs_cache }}"
      state: merged
    become: true
    when: ansible_network_os == 'iosxr'
  
  - name: write interface to Cisco NXOS 
    nxos_interfaces: 
      config: "{{ _intfs_cache }}"
      state: merged
    when: ansible_network_os == 'nxos'

