---

- name: PUSH INTERFACE CONFIGS TO DEVICES TEST OPER STATE AND ROLLBACK
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    - ping_test_destination: "10.10.100.104"

  tasks:
    
  - name: "2.0: Cisco IOS Devices"
    block:
    - name: "2.1: write interface attributes to Cisco IOS"
      cisco.ios.ios_interfaces: 
        config: "{{ intfs.interfaces }}"
        state: replaced
      register: _result_ios_interfaces
    - name: "2.2: write interface L3 config to Cisco IOS"
      cisco.ios.ios_l3_interfaces: 
        config: "{{ intfs.l3_interfaces }}"
        state: replaced
      register: _result_ios_l3_interfaces
    - name: "2.3: write VLAN config to IOS Switch"
      cisco.ios.ios_vlans:
        config: "{{ intfs.vlans }}"
        state: merged
      register: _result_ios_vlan
      when: inventory_hostname in groups['switch']
    - name: "2.4: write interface L2 config to Cisco IOS Switch"
      cisco.ios.ios_l2_interfaces: 
        config: "{{ intfs.l2_interfaces }}"
        state: replaced
      register: _result_ios_l2_interfaces
      when: inventory_hostname in groups['switch']
    become: true
    when: ansible_network_os == 'ios'
  
  - name: "3.0: Cisco IOS XR Devices"
    block:
    - name: "3.1: write interface attributes to Cisco IOS XR"
      cisco.iosxr.iosxr_interfaces: 
        config: "{{ intfs.interfaces }}"
        state: replaced
      when: intfs.interfaces is defined
    - name: "3.2: write interface L3 config to Cisco IOS XR"
      cisco.iosxr.iosxr_l3_interfaces: 
        config: "{{ intfs.l3_interfaces }}"
        state: replaced
      when: intfs.l3_interfaces is defined
    become: true
    when: ansible_network_os == 'iosxr'

  - name: "4.0: Cisco Nexus Devices"
    block:
    - name: "4.1: write interface attributes to Cisco Nexus"
      cisco.nxos.nxos_interfaces: 
        config: "{{ intfs.interfaces }}"
        state: replaced
    # VLAN ID 1 not allowed by module, therefor filtered
    - name: "4.2: write VLAN config to Cisco Nexus"
      cisco.nxos.nxos_vlans: 
        config: "{{ intfs.vlans | json_query('[?vlan_id!=`1`]') }}"
        state: overridden
      when: intfs.vlans is defined and (intfs.vlans | length) > 1
    - name: "4.3: write L2 interface config to Cisco Nexus"
      cisco.nxos.nxos_l2_interfaces: 
        config: "{{ intfs.l2_interfaces }}"
        state: replaced
      when: intfs.l2_interfaces is defined
    # interface mgmt not allowed by module, therefor filtered
    - name: "4.4: write interface L3 config to Cisco Nexus"
      cisco.nxos.nxos_l3_interfaces: 
        config: "{{ intfs.l3_interfaces | json_query('[?name!=`mgmt0`]') }}"
        state: merged
    when: ansible_network_os == 'nxos'

  - name: "5.0: test operational state"
    block:
      - name: ping from IOS device to IOSXR
        cisco.ios.ios_ping:
          dest: "{{ ping_test_destination }}"
          count: 3
        become: true
        when: ansible_network_os == 'ios' and inventory_hostname in groups['router']
    rescue:
      - name: "5.1: rollback IOS interface config"
        cisco.ios.ios_interfaces:
          config: "{{ _result_ios_interfaces.before }}"
          state: replaced
        become: true
        when: _result_ios_interfaces.changed
      - name: "5.2: rollback IOS L3 interface config"
        cisco.ios.ios_l3_interfaces: 
          config: "{{ _result_ios_l3_interfaces.before }}"
          state: replaced
        become: true
        when: _result_ios_l3_interfaces.changed
