---

- name: PUSH CONFIGS TO DEVICES TEST OPER STATE AND ROLLBACK
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    
  - name: "2.0: Cisco IOS Devices"
    block:
    - name: "2.1: write interface attributes to Cisco IOS"
      ios_interfaces: 
        config: "{{ intfs.interfaces }}"
        state: replaced
    - name: "2.2: write interface L3 config to Cisco IOS"
      ios_l3_interfaces: 
        config: "{{ intfs.l3_interfaces }}"
        state: merged
    - name: "2.3: write VLAN config to IOS Switch"
      ios_vlans:
        config: "{{ intfs.vlans }}"
        state: merged
      register: _result_ios_vlan
      when: inventory_hostname in groups['switch']
    - name: "2.4: write interface L2 config to Cisco IOS Switch"
      ios_l2_interfaces: 
        config: "{{ intfs.l2_interfaces }}"
        state: replaced
      register: _result_ios_l2_interfaces
      when: inventory_hostname in groups['switch']
    become: true
    when: ansible_network_os == 'ios'
  
  - name: "3.0: Cisco IOS XR Devices"
    block:
    - name: "3.1: write interface attributes to Cisco IOS XR"
      iosxr_interfaces: 
        config: "{{ intfs.interfaces }}"
        state: merged
    - name: "3.2: write interface L3 config to Cisco IOS XR"
      iosxr_l3_interfaces: 
        config: "{{ intfs.l3_interfaces }}"
        state: merged
    become: true
    when: ansible_network_os == 'iosxr'

  - name: "4.0: Cisco Nexus Devices"
    block:
    - name: "4.1: write interface attributes to Cisco Nexus"
      nxos_interfaces: 
        config: "{{ intfs.interfaces }}"
        state: replaced
    # VLAN ID 1 not allowed by module, therefor filtered
    - name: "4.2: write VLAN config to Cisco Nexus"
      nxos_vlans: 
        config: "{{ intfs.vlans | json_query('[?vlan_id!=`1`]') }}"
        state: overridden
      when: intfs.vlans is defined
    - name: "4.3: write L2 interface config to Cisco Nexus"
      nxos_l2_interfaces: 
        config: "{{ intfs.l2_interfaces }}"
        state: replaced
      when: intfs.l2_interfaces is defined
    # interface mgmt not allowed by module, therefor filtered
    - name: "4.4: write interface L3 config to Cisco Nexus"
      nxos_l3_interfaces: 
        config: "{{ intfs.l3_interfaces | json_query('[?name!=`mgmt0`]') }}"
        state: merged
    when: ansible_network_os == 'nxos'

  - name: "5.0: test operational state"
    block:
      - name: ping from IOS device to IOSXR
        ios_ping:
          dest: 10.10.100.104
          count: 3
        become: true
    when: ansible_network_os == 'ios' and inventory_hostname in groups['router']
    rescue:
      - name: "5.1: rollback L2 interface config"
        ios_l2_interfaces:
          config: "{{ _result_ios_l2_interfaces.before }}"
          state: replaced
        when: _result_ios_l2_interfaces.changed
      - name: "5.2: rollback VLAN config"
        ios_vlans: 
          config: "{{ _result_ios_vlan.before }}"
          state: replaced
        when: _result_ios_vlan.changed
      




        