---
# pushes L3 interface config from Netbox IPAM
# to IOS devices

- name: Configure network interfaces
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    - _netbox_url: "https://172.16.1.17"
    - _netbox_api_token: "0123456789abcdef0123456789abcdef01234567"
    - device_id: 45
    - interface_filter: ""

  tasks:

    - name: get netbox json
      uri:
        url: "{{ _netbox_url }}/api/dcim/interfaces/?device_id={{ device_id }}"
        method: GET
        validate_certs: no
        headers:
          content-type: 'aplication/json'
          Authorization: "Token {{ _netbox_api_token }}"
        body_format: json
      register: host_info
      delegate_to: localhost
    
    - debug:
        var: host_info.json.results
        verbosity: 2
    
    - name: Configure interface L2 access VLAN 
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            access:
              vlan: "{{ item.untagged_vlan.vid }}"
        state: replaced
      loop: "{{ host_info.json.results }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.mode is defined and item.mode.value is defined and item.mode.value == 'access'
      become: yes